// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/sanction/v1beta1/query.proto

package sanction

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryIsSanctionedRequest defines the RPC request for checking if an account is sanctioned.
type QueryIsSanctionedRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryIsSanctionedRequest) Reset()         { *m = QueryIsSanctionedRequest{} }
func (m *QueryIsSanctionedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsSanctionedRequest) ProtoMessage()    {}
func (*QueryIsSanctionedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{0}
}
func (m *QueryIsSanctionedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsSanctionedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsSanctionedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsSanctionedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsSanctionedRequest.Merge(m, src)
}
func (m *QueryIsSanctionedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsSanctionedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsSanctionedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsSanctionedRequest proto.InternalMessageInfo

func (m *QueryIsSanctionedRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryIsSanctionedResponse defines the RPC response of an IsSanctioned query.
type QueryIsSanctionedResponse struct {
	// is_sanctioned is true if the address is sanctioned.
	IsSanctioned bool `protobuf:"varint,1,opt,name=is_sanctioned,json=isSanctioned,proto3" json:"is_sanctioned,omitempty"`
}

func (m *QueryIsSanctionedResponse) Reset()         { *m = QueryIsSanctionedResponse{} }
func (m *QueryIsSanctionedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsSanctionedResponse) ProtoMessage()    {}
func (*QueryIsSanctionedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{1}
}
func (m *QueryIsSanctionedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsSanctionedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsSanctionedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsSanctionedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsSanctionedResponse.Merge(m, src)
}
func (m *QueryIsSanctionedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsSanctionedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsSanctionedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsSanctionedResponse proto.InternalMessageInfo

func (m *QueryIsSanctionedResponse) GetIsSanctioned() bool {
	if m != nil {
		return m.IsSanctioned
	}
	return false
}

// QuerySanctionedAddressesRequest defines the RPC request for listing sanctioned accounts.
type QuerySanctionedAddressesRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,99,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySanctionedAddressesRequest) Reset()         { *m = QuerySanctionedAddressesRequest{} }
func (m *QuerySanctionedAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySanctionedAddressesRequest) ProtoMessage()    {}
func (*QuerySanctionedAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{2}
}
func (m *QuerySanctionedAddressesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySanctionedAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySanctionedAddressesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySanctionedAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySanctionedAddressesRequest.Merge(m, src)
}
func (m *QuerySanctionedAddressesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySanctionedAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySanctionedAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySanctionedAddressesRequest proto.InternalMessageInfo

func (m *QuerySanctionedAddressesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySanctionedAddressesResponse defines the RPC response of a SanctionedAddresses query.
type QuerySanctionedAddressesResponse struct {
	// addresses is the list of sanctioned account addresses.
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,99,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySanctionedAddressesResponse) Reset()         { *m = QuerySanctionedAddressesResponse{} }
func (m *QuerySanctionedAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySanctionedAddressesResponse) ProtoMessage()    {}
func (*QuerySanctionedAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{3}
}
func (m *QuerySanctionedAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySanctionedAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySanctionedAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySanctionedAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySanctionedAddressesResponse.Merge(m, src)
}
func (m *QuerySanctionedAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySanctionedAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySanctionedAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySanctionedAddressesResponse proto.InternalMessageInfo

func (m *QuerySanctionedAddressesResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *QuerySanctionedAddressesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTemporaryEntriesRequest defines the RPC request for listing temporary sanction/unsanction entries.
type QueryTemporaryEntriesRequest struct {
	// address is an optional address to restrict results to.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,99,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTemporaryEntriesRequest) Reset()         { *m = QueryTemporaryEntriesRequest{} }
func (m *QueryTemporaryEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTemporaryEntriesRequest) ProtoMessage()    {}
func (*QueryTemporaryEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{4}
}
func (m *QueryTemporaryEntriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemporaryEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemporaryEntriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemporaryEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemporaryEntriesRequest.Merge(m, src)
}
func (m *QueryTemporaryEntriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemporaryEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemporaryEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemporaryEntriesRequest proto.InternalMessageInfo

func (m *QueryTemporaryEntriesRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryTemporaryEntriesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTemporaryEntriesResponse defines the RPC response of a TemporaryEntries query.
type QueryTemporaryEntriesResponse struct {
	Entries []*TemporaryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,99,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTemporaryEntriesResponse) Reset()         { *m = QueryTemporaryEntriesResponse{} }
func (m *QueryTemporaryEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTemporaryEntriesResponse) ProtoMessage()    {}
func (*QueryTemporaryEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{5}
}
func (m *QueryTemporaryEntriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemporaryEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemporaryEntriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemporaryEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemporaryEntriesResponse.Merge(m, src)
}
func (m *QueryTemporaryEntriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemporaryEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemporaryEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemporaryEntriesResponse proto.InternalMessageInfo

func (m *QueryTemporaryEntriesResponse) GetEntries() []*TemporaryEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *QueryTemporaryEntriesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryParamsRequest defines the RPC request for getting the sanction module params.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{6}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse defines the RPC response of a Params query.
type QueryParamsResponse struct {
	// params are the sanction module parameters.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9fc7de93fcbdc3, []int{7}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryIsSanctionedRequest)(nil), "cosmos.sanction.v1beta1.QueryIsSanctionedRequest")
	proto.RegisterType((*QueryIsSanctionedResponse)(nil), "cosmos.sanction.v1beta1.QueryIsSanctionedResponse")
	proto.RegisterType((*QuerySanctionedAddressesRequest)(nil), "cosmos.sanction.v1beta1.QuerySanctionedAddressesRequest")
	proto.RegisterType((*QuerySanctionedAddressesResponse)(nil), "cosmos.sanction.v1beta1.QuerySanctionedAddressesResponse")
	proto.RegisterType((*QueryTemporaryEntriesRequest)(nil), "cosmos.sanction.v1beta1.QueryTemporaryEntriesRequest")
	proto.RegisterType((*QueryTemporaryEntriesResponse)(nil), "cosmos.sanction.v1beta1.QueryTemporaryEntriesResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.sanction.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.sanction.v1beta1.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("cosmos/sanction/v1beta1/query.proto", fileDescriptor_9d9fc7de93fcbdc3)
}

var fileDescriptor_9d9fc7de93fcbdc3 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xbf, 0x6f, 0x13, 0x31,
	0x14, 0xc7, 0x63, 0x50, 0x53, 0xfa, 0x5a, 0x24, 0xe4, 0x56, 0x22, 0x3d, 0xa5, 0x97, 0x70, 0x85,
	0xa6, 0x50, 0x7a, 0xa7, 0x04, 0x51, 0x60, 0x23, 0x95, 0x00, 0xb1, 0x54, 0x25, 0x65, 0x62, 0xa9,
	0x9c, 0xc4, 0x3a, 0x4e, 0xe4, 0xce, 0xd7, 0xb3, 0x53, 0x11, 0x21, 0x16, 0x66, 0x06, 0x24, 0x36,
	0x16, 0x06, 0x16, 0x24, 0x16, 0x06, 0xfe, 0x08, 0xc6, 0x0a, 0x16, 0x46, 0x94, 0xf0, 0x87, 0xa0,
	0xd8, 0xbe, 0xfc, 0xa8, 0xe2, 0x40, 0xab, 0x4e, 0x51, 0xec, 0xef, 0xfb, 0xbe, 0x8f, 0xbe, 0x7e,
	0x2f, 0x81, 0xd5, 0x06, 0xe3, 0x21, 0xe3, 0x1e, 0x27, 0x51, 0x43, 0x04, 0x2c, 0xf2, 0x0e, 0xcb,
	0x75, 0x2a, 0x48, 0xd9, 0x3b, 0x68, 0xd3, 0xa4, 0xe3, 0xc6, 0x09, 0x13, 0x0c, 0x5f, 0x56, 0x22,
	0x37, 0x15, 0xb9, 0x5a, 0x64, 0xdd, 0xd0, 0xd5, 0x75, 0xc2, 0xa9, 0xaa, 0x18, 0xd4, 0xc7, 0xc4,
	0x0f, 0x22, 0x22, 0xd5, 0xd2, 0xc4, 0x5a, 0x33, 0x75, 0x1a, 0xb8, 0x2a, 0xdd, 0xb2, 0xd2, 0xed,
	0xcb, 0x6f, 0x9e, 0xee, 0xac, 0xae, 0xf2, 0x3e, 0x63, 0x7e, 0x8b, 0x7a, 0x24, 0x0e, 0x3c, 0x12,
	0x45, 0x4c, 0x48, 0x7f, 0x7d, 0xeb, 0xec, 0x40, 0xee, 0x49, 0x1f, 0xe1, 0x31, 0xdf, 0xd3, 0x8e,
	0xb4, 0x59, 0xa3, 0x07, 0x6d, 0xca, 0x05, 0xae, 0xc0, 0x2c, 0x69, 0x36, 0x13, 0xca, 0x79, 0x0e,
	0x15, 0xd1, 0xfa, 0xdc, 0x76, 0xee, 0xc7, 0xb7, 0xcd, 0x25, 0x6d, 0x5e, 0x55, 0x37, 0x7b, 0x22,
	0x09, 0x22, 0xbf, 0x96, 0x0a, 0x9d, 0xfb, 0xb0, 0x3c, 0xc1, 0x8f, 0xc7, 0x2c, 0xe2, 0x14, 0xaf,
	0xc2, 0xc5, 0x80, 0xef, 0xf3, 0xc1, 0x85, 0xb4, 0xbd, 0x50, 0x5b, 0x08, 0x46, 0xc4, 0x4e, 0x00,
	0x05, 0xe9, 0x30, 0x3c, 0xd2, 0xad, 0x28, 0x4f, 0xc1, 0x1e, 0x02, 0x0c, 0x93, 0xca, 0x35, 0x8a,
	0x68, 0x7d, 0xbe, 0xb2, 0xe6, 0x6a, 0xb0, 0x7e, 0xac, 0xae, 0x7a, 0x08, 0x1d, 0x96, 0xbb, 0x4b,
	0x7c, 0xaa, 0x6b, 0x6b, 0x23, 0x95, 0xce, 0x27, 0x04, 0x45, 0x73, 0x2f, 0x0d, 0xbd, 0x05, 0x73,
	0x24, 0x3d, 0xcc, 0xa1, 0xe2, 0xf9, 0xa9, 0x39, 0x0c, 0xa5, 0xf8, 0xd1, 0x04, 0xc8, 0xd2, 0x3f,
	0x21, 0x55, 0xd3, 0x31, 0xca, 0x0f, 0x08, 0xf2, 0x92, 0xf2, 0x29, 0x0d, 0x63, 0x96, 0x90, 0xa4,
	0xf3, 0x20, 0x12, 0x49, 0x30, 0x8c, 0xe3, 0x14, 0xef, 0x74, 0x66, 0x11, 0x7e, 0x41, 0xb0, 0x62,
	0x80, 0xd3, 0xf9, 0x55, 0x61, 0x96, 0xaa, 0x23, 0x99, 0xde, 0x48, 0x08, 0xc7, 0x37, 0xc3, 0x1d,
	0xf3, 0xe8, 0xd4, 0xd2, 0xba, 0xb3, 0x8b, 0x72, 0x09, 0xb0, 0x84, 0xdd, 0x25, 0x09, 0x09, 0xd3,
	0xfc, 0x9c, 0x1d, 0x58, 0x1c, 0x3b, 0xd5, 0xe0, 0x77, 0x20, 0x1b, 0xcb, 0x13, 0x99, 0xea, 0x7c,
	0xa5, 0x60, 0xe4, 0xd6, 0x85, 0x5a, 0x5e, 0xf9, 0x38, 0x03, 0x33, 0xd2, 0x10, 0x7f, 0x46, 0xb0,
	0x30, 0xba, 0x09, 0xb8, 0x6c, 0xf4, 0x30, 0x6d, 0xa1, 0x55, 0x39, 0x49, 0x89, 0x42, 0x77, 0xca,
	0x6f, 0x7e, 0xfe, 0x79, 0x7f, 0x6e, 0x03, 0x5f, 0xf7, 0x4c, 0xbf, 0x1f, 0xa4, 0x21, 0x82, 0x43,
	0xea, 0xbd, 0xd2, 0xf3, 0xf0, 0x1a, 0x7f, 0x45, 0xb0, 0x38, 0x61, 0x0d, 0xf0, 0xdd, 0xe9, 0xed,
	0xcd, 0x5b, 0x6a, 0xdd, 0x3b, 0x45, 0xa5, 0xe6, 0xbf, 0x2a, 0xf9, 0x6d, 0x9c, 0x37, 0xf3, 0xb7,
	0x5a, 0xfd, 0x74, 0x2f, 0x1d, 0x1f, 0x3b, 0x7c, 0x7b, 0x7a, 0x57, 0xc3, 0x0e, 0x59, 0x5b, 0x27,
	0x2d, 0xd3, 0xa4, 0xd7, 0x24, 0x69, 0x01, 0xaf, 0x18, 0x49, 0x05, 0x0d, 0x63, 0xfc, 0x16, 0x41,
	0x56, 0x4d, 0x09, 0xde, 0x98, 0xde, 0x69, 0x6c, 0x34, 0xad, 0x9b, 0xff, 0x27, 0xd6, 0x30, 0x25,
	0x09, 0x73, 0x05, 0x17, 0x8c, 0x30, 0x6a, 0x42, 0xb7, 0xab, 0xdf, 0xbb, 0x36, 0x3a, 0xea, 0xda,
	0xe8, 0x77, 0xd7, 0x46, 0xef, 0x7a, 0x76, 0xe6, 0xa8, 0x67, 0x67, 0x7e, 0xf5, 0xec, 0xcc, 0xb3,
	0x92, 0x1f, 0x88, 0xe7, 0xed, 0xba, 0xdb, 0x60, 0x61, 0x6a, 0xa2, 0x3e, 0x36, 0x79, 0xf3, 0x85,
	0xf7, 0x72, 0xe0, 0x58, 0xcf, 0xca, 0xff, 0x8f, 0x5b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0x2f, 0x12, 0xc1, 0x0c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// IsSanctioned checks if an account has been sanctioned.
	IsSanctioned(ctx context.Context, in *QueryIsSanctionedRequest, opts ...grpc.CallOption) (*QueryIsSanctionedResponse, error)
	// SanctionedAddresses returns a list of sanctioned addresses.
	SanctionedAddresses(ctx context.Context, in *QuerySanctionedAddressesRequest, opts ...grpc.CallOption) (*QuerySanctionedAddressesResponse, error)
	TemporaryEntries(ctx context.Context, in *QueryTemporaryEntriesRequest, opts ...grpc.CallOption) (*QueryTemporaryEntriesResponse, error)
	// Params returns the sanction module's params.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) IsSanctioned(ctx context.Context, in *QueryIsSanctionedRequest, opts ...grpc.CallOption) (*QueryIsSanctionedResponse, error) {
	out := new(QueryIsSanctionedResponse)
	err := c.cc.Invoke(ctx, "/cosmos.sanction.v1beta1.Query/IsSanctioned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SanctionedAddresses(ctx context.Context, in *QuerySanctionedAddressesRequest, opts ...grpc.CallOption) (*QuerySanctionedAddressesResponse, error) {
	out := new(QuerySanctionedAddressesResponse)
	err := c.cc.Invoke(ctx, "/cosmos.sanction.v1beta1.Query/SanctionedAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TemporaryEntries(ctx context.Context, in *QueryTemporaryEntriesRequest, opts ...grpc.CallOption) (*QueryTemporaryEntriesResponse, error) {
	out := new(QueryTemporaryEntriesResponse)
	err := c.cc.Invoke(ctx, "/cosmos.sanction.v1beta1.Query/TemporaryEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.sanction.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// IsSanctioned checks if an account has been sanctioned.
	IsSanctioned(context.Context, *QueryIsSanctionedRequest) (*QueryIsSanctionedResponse, error)
	// SanctionedAddresses returns a list of sanctioned addresses.
	SanctionedAddresses(context.Context, *QuerySanctionedAddressesRequest) (*QuerySanctionedAddressesResponse, error)
	TemporaryEntries(context.Context, *QueryTemporaryEntriesRequest) (*QueryTemporaryEntriesResponse, error)
	// Params returns the sanction module's params.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) IsSanctioned(ctx context.Context, req *QueryIsSanctionedRequest) (*QueryIsSanctionedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSanctioned not implemented")
}
func (*UnimplementedQueryServer) SanctionedAddresses(ctx context.Context, req *QuerySanctionedAddressesRequest) (*QuerySanctionedAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SanctionedAddresses not implemented")
}
func (*UnimplementedQueryServer) TemporaryEntries(ctx context.Context, req *QueryTemporaryEntriesRequest) (*QueryTemporaryEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TemporaryEntries not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_IsSanctioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsSanctionedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsSanctioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.sanction.v1beta1.Query/IsSanctioned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsSanctioned(ctx, req.(*QueryIsSanctionedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SanctionedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySanctionedAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SanctionedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.sanction.v1beta1.Query/SanctionedAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SanctionedAddresses(ctx, req.(*QuerySanctionedAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TemporaryEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTemporaryEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TemporaryEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.sanction.v1beta1.Query/TemporaryEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TemporaryEntries(ctx, req.(*QueryTemporaryEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.sanction.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.sanction.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsSanctioned",
			Handler:    _Query_IsSanctioned_Handler,
		},
		{
			MethodName: "SanctionedAddresses",
			Handler:    _Query_SanctionedAddresses_Handler,
		},
		{
			MethodName: "TemporaryEntries",
			Handler:    _Query_TemporaryEntries_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/sanction/v1beta1/query.proto",
}

func (m *QueryIsSanctionedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsSanctionedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsSanctionedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIsSanctionedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsSanctionedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsSanctionedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsSanctioned {
		i--
		if m.IsSanctioned {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QuerySanctionedAddressesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySanctionedAddressesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySanctionedAddressesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0x9a
	}
	return len(dAtA) - i, nil
}

func (m *QuerySanctionedAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySanctionedAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySanctionedAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0x9a
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTemporaryEntriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemporaryEntriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemporaryEntriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0x9a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTemporaryEntriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemporaryEntriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemporaryEntriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0x9a
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIsSanctionedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIsSanctionedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsSanctioned {
		n += 2
	}
	return n
}

func (m *QuerySanctionedAddressesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySanctionedAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTemporaryEntriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTemporaryEntriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIsSanctionedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsSanctionedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsSanctionedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsSanctionedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsSanctionedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsSanctionedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSanctioned", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSanctioned = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySanctionedAddressesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySanctionedAddressesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySanctionedAddressesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySanctionedAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySanctionedAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySanctionedAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTemporaryEntriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemporaryEntriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemporaryEntriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTemporaryEntriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemporaryEntriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemporaryEntriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &TemporaryEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
