// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/quarantine/v1beta1/tx.proto

package quarantine

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgQuarantineOptIn represents a message for opting in to account quarantine.
type MsgQuarantineOptIn struct {
	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (m *MsgQuarantineOptIn) Reset()         { *m = MsgQuarantineOptIn{} }
func (m *MsgQuarantineOptIn) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineOptIn) ProtoMessage()    {}
func (*MsgQuarantineOptIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{0}
}
func (m *MsgQuarantineOptIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineOptIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineOptIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineOptIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineOptIn.Merge(m, src)
}
func (m *MsgQuarantineOptIn) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineOptIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineOptIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineOptIn proto.InternalMessageInfo

func (m *MsgQuarantineOptIn) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

// MsgQuarantineOptInResponse defines the Msg/QuarantineOpt response type.
type MsgQuarantineOptInResponse struct {
}

func (m *MsgQuarantineOptInResponse) Reset()         { *m = MsgQuarantineOptInResponse{} }
func (m *MsgQuarantineOptInResponse) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineOptInResponse) ProtoMessage()    {}
func (*MsgQuarantineOptInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{1}
}
func (m *MsgQuarantineOptInResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineOptInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineOptInResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineOptInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineOptInResponse.Merge(m, src)
}
func (m *MsgQuarantineOptInResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineOptInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineOptInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineOptInResponse proto.InternalMessageInfo

// MsgQuarantineOptIn represents a message for opting in to account quarantine.
type MsgQuarantineOptOut struct {
	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (m *MsgQuarantineOptOut) Reset()         { *m = MsgQuarantineOptOut{} }
func (m *MsgQuarantineOptOut) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineOptOut) ProtoMessage()    {}
func (*MsgQuarantineOptOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{2}
}
func (m *MsgQuarantineOptOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineOptOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineOptOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineOptOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineOptOut.Merge(m, src)
}
func (m *MsgQuarantineOptOut) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineOptOut) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineOptOut.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineOptOut proto.InternalMessageInfo

func (m *MsgQuarantineOptOut) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

// MsgQuarantineOptInResponse defines the Msg/QuarantineOpt response type.
type MsgQuarantineOptOutResponse struct {
}

func (m *MsgQuarantineOptOutResponse) Reset()         { *m = MsgQuarantineOptOutResponse{} }
func (m *MsgQuarantineOptOutResponse) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineOptOutResponse) ProtoMessage()    {}
func (*MsgQuarantineOptOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{3}
}
func (m *MsgQuarantineOptOutResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineOptOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineOptOutResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineOptOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineOptOutResponse.Merge(m, src)
}
func (m *MsgQuarantineOptOutResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineOptOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineOptOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineOptOutResponse proto.InternalMessageInfo

// MsgQuarantineAccept represents a message for accepting quarantined funds.
type MsgQuarantineAccept struct {
	ToAddress   string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// permanent, if true, causes current and future sends from from_address to to_address to be automatically accepted.
	// If false (default), only the currently quarantined funds will be accepted.
	Permanent bool `protobuf:"varint,3,opt,name=permanent,proto3" json:"permanent,omitempty"`
}

func (m *MsgQuarantineAccept) Reset()         { *m = MsgQuarantineAccept{} }
func (m *MsgQuarantineAccept) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineAccept) ProtoMessage()    {}
func (*MsgQuarantineAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{4}
}
func (m *MsgQuarantineAccept) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineAccept.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineAccept.Merge(m, src)
}
func (m *MsgQuarantineAccept) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineAccept.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineAccept proto.InternalMessageInfo

func (m *MsgQuarantineAccept) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgQuarantineAccept) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgQuarantineAccept) GetPermanent() bool {
	if m != nil {
		return m.Permanent
	}
	return false
}

// MsgQuarantineAcceptResponse defines the Msg/QuarantineAccept response type.
type MsgQuarantineAcceptResponse struct {
}

func (m *MsgQuarantineAcceptResponse) Reset()         { *m = MsgQuarantineAcceptResponse{} }
func (m *MsgQuarantineAcceptResponse) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineAcceptResponse) ProtoMessage()    {}
func (*MsgQuarantineAcceptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{5}
}
func (m *MsgQuarantineAcceptResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineAcceptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineAcceptResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineAcceptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineAcceptResponse.Merge(m, src)
}
func (m *MsgQuarantineAcceptResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineAcceptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineAcceptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineAcceptResponse proto.InternalMessageInfo

// MsgQuarantineDecline represents a message for declining quarantined funds.
type MsgQuarantineDecline struct {
	ToAddress   string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// permanent, if true, causes current and future sends from from_address to to_address to be automatically declined.
	// If false (default), only the currently quarantined funds will be declined.
	Permanent bool `protobuf:"varint,3,opt,name=permanent,proto3" json:"permanent,omitempty"`
}

func (m *MsgQuarantineDecline) Reset()         { *m = MsgQuarantineDecline{} }
func (m *MsgQuarantineDecline) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineDecline) ProtoMessage()    {}
func (*MsgQuarantineDecline) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{6}
}
func (m *MsgQuarantineDecline) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineDecline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineDecline.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineDecline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineDecline.Merge(m, src)
}
func (m *MsgQuarantineDecline) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineDecline) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineDecline.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineDecline proto.InternalMessageInfo

func (m *MsgQuarantineDecline) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgQuarantineDecline) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgQuarantineDecline) GetPermanent() bool {
	if m != nil {
		return m.Permanent
	}
	return false
}

// MsgQuarantineDeclineResponse defines the Msg/QuarantineDecline response type.
type MsgQuarantineDeclineResponse struct {
}

func (m *MsgQuarantineDeclineResponse) Reset()         { *m = MsgQuarantineDeclineResponse{} }
func (m *MsgQuarantineDeclineResponse) String() string { return proto.CompactTextString(m) }
func (*MsgQuarantineDeclineResponse) ProtoMessage()    {}
func (*MsgQuarantineDeclineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{7}
}
func (m *MsgQuarantineDeclineResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuarantineDeclineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuarantineDeclineResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuarantineDeclineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuarantineDeclineResponse.Merge(m, src)
}
func (m *MsgQuarantineDeclineResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuarantineDeclineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuarantineDeclineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuarantineDeclineResponse proto.InternalMessageInfo

// MsgUpdateQuarantineAutoResponse represents a message for updating quarantine auto-responses for a receiving address.
type MsgUpdateQuarantineAutoResponses struct {
	// to_address is the quarantined address that would be accepting or declining funds.
	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// updates is the list of addresses and actions that should be updated for the to_address.
	Updates []*QuarantineAutoResponseUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (m *MsgUpdateQuarantineAutoResponses) Reset()         { *m = MsgUpdateQuarantineAutoResponses{} }
func (m *MsgUpdateQuarantineAutoResponses) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateQuarantineAutoResponses) ProtoMessage()    {}
func (*MsgUpdateQuarantineAutoResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{8}
}
func (m *MsgUpdateQuarantineAutoResponses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateQuarantineAutoResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateQuarantineAutoResponses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateQuarantineAutoResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateQuarantineAutoResponses.Merge(m, src)
}
func (m *MsgUpdateQuarantineAutoResponses) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateQuarantineAutoResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateQuarantineAutoResponses.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateQuarantineAutoResponses proto.InternalMessageInfo

func (m *MsgUpdateQuarantineAutoResponses) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgUpdateQuarantineAutoResponses) GetUpdates() []*QuarantineAutoResponseUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

// MsgUpdateQuarantineAutoResponsesResponse defines the Msg/UpdateQuarantineAutoResponse response type.
type MsgUpdateQuarantineAutoResponsesResponse struct {
}

func (m *MsgUpdateQuarantineAutoResponsesResponse) Reset() {
	*m = MsgUpdateQuarantineAutoResponsesResponse{}
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateQuarantineAutoResponsesResponse) ProtoMessage()    {}
func (*MsgUpdateQuarantineAutoResponsesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d4535ca5d9aa17, []int{9}
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateQuarantineAutoResponsesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateQuarantineAutoResponsesResponse.Merge(m, src)
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateQuarantineAutoResponsesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateQuarantineAutoResponsesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgQuarantineOptIn)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineOptIn")
	proto.RegisterType((*MsgQuarantineOptInResponse)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineOptInResponse")
	proto.RegisterType((*MsgQuarantineOptOut)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineOptOut")
	proto.RegisterType((*MsgQuarantineOptOutResponse)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineOptOutResponse")
	proto.RegisterType((*MsgQuarantineAccept)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineAccept")
	proto.RegisterType((*MsgQuarantineAcceptResponse)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineAcceptResponse")
	proto.RegisterType((*MsgQuarantineDecline)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineDecline")
	proto.RegisterType((*MsgQuarantineDeclineResponse)(nil), "cosmos.quarantine.v1beta1.MsgQuarantineDeclineResponse")
	proto.RegisterType((*MsgUpdateQuarantineAutoResponses)(nil), "cosmos.quarantine.v1beta1.MsgUpdateQuarantineAutoResponses")
	proto.RegisterType((*MsgUpdateQuarantineAutoResponsesResponse)(nil), "cosmos.quarantine.v1beta1.MsgUpdateQuarantineAutoResponsesResponse")
}

func init() {
	proto.RegisterFile("cosmos/quarantine/v1beta1/tx.proto", fileDescriptor_d2d4535ca5d9aa17)
}

var fileDescriptor_d2d4535ca5d9aa17 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xbf, 0x6f, 0xd3, 0x40,
	0x18, 0xcd, 0x11, 0xf1, 0x23, 0x5f, 0x91, 0x0a, 0xa6, 0x12, 0xc1, 0xa4, 0x56, 0x94, 0x29, 0x44,
	0x8a, 0x4f, 0x29, 0x82, 0x48, 0x74, 0x6a, 0xcb, 0xc2, 0x10, 0x45, 0x0d, 0x62, 0x61, 0x20, 0xba,
	0x38, 0x87, 0xb1, 0xc0, 0x77, 0xae, 0xef, 0x5c, 0x0a, 0x12, 0x0b, 0x7f, 0x01, 0x2b, 0x23, 0xff,
	0x01, 0x03, 0x13, 0x0c, 0xac, 0x8c, 0x15, 0x13, 0x23, 0x4a, 0x06, 0xfe, 0x0d, 0x94, 0xf8, 0xec,
	0xa6, 0xb1, 0xeb, 0xc4, 0x81, 0xa5, 0xd3, 0xfd, 0xf8, 0xde, 0xfb, 0xde, 0x7b, 0x96, 0x3f, 0x1d,
	0xd4, 0x2c, 0x2e, 0x5c, 0x2e, 0xf0, 0x41, 0x40, 0x7c, 0xc2, 0xa4, 0xc3, 0x28, 0x3e, 0x6c, 0x0d,
	0xa8, 0x24, 0x2d, 0x2c, 0x8f, 0x4c, 0xcf, 0xe7, 0x92, 0x6b, 0xb7, 0x42, 0x8c, 0x79, 0x82, 0x31,
	0x15, 0x46, 0x6f, 0x28, 0xfa, 0x80, 0x08, 0x8a, 0x0f, 0x02, 0xea, 0xbf, 0x89, 0xe9, 0x1e, 0xb1,
	0x1d, 0x46, 0xa4, 0xc3, 0x59, 0xd8, 0x46, 0xbf, 0xa9, 0xb0, 0xae, 0xb0, 0xf1, 0x61, 0x6b, 0xb2,
	0xa8, 0x42, 0xe3, 0x6c, 0x0f, 0x33, 0x92, 0x21, 0x56, 0x79, 0xe9, 0x4f, 0x4f, 0x58, 0x19, 0x9b,
	0x1e, 0x6a, 0xcf, 0x40, 0xeb, 0x08, 0x7b, 0x3f, 0x66, 0x74, 0x3d, 0xf9, 0x88, 0x69, 0x6d, 0x00,
	0xc9, 0xfb, 0x64, 0x38, 0xf4, 0xa9, 0x10, 0x65, 0x54, 0x45, 0xf5, 0xd2, 0x6e, 0xf9, 0xe7, 0x97,
	0xe6, 0x86, 0xe2, 0xee, 0x84, 0x95, 0xc7, 0xd2, 0x77, 0x98, 0xdd, 0x2b, 0x49, 0xae, 0x2e, 0x1e,
	0xac, 0xbf, 0xff, 0xf3, 0xb9, 0x31, 0xc3, 0xad, 0x55, 0x40, 0x4f, 0xf6, 0xef, 0x51, 0xe1, 0x71,
	0x26, 0x68, 0xad, 0x0f, 0x37, 0xe6, 0xab, 0xdd, 0x40, 0xfe, 0x47, 0xf9, 0x4d, 0xb8, 0x9d, 0x22,
	0x10, 0xeb, 0x7f, 0x45, 0x73, 0x06, 0x76, 0x2c, 0x8b, 0x7a, 0xab, 0x1b, 0xd0, 0xb6, 0xe1, 0xea,
	0x73, 0x9f, 0xbb, 0x31, 0xf5, 0xc2, 0x02, 0xea, 0xda, 0x04, 0x1d, 0x91, 0x2b, 0x50, 0xf2, 0xa8,
	0xef, 0x12, 0x46, 0x99, 0x2c, 0x17, 0xab, 0xa8, 0x7e, 0xa5, 0x77, 0x72, 0xb1, 0x38, 0x5b, 0xe8,
	0x3d, 0xce, 0xf6, 0x0d, 0xc1, 0xc6, 0xa9, 0xfa, 0x43, 0x6a, 0xbd, 0x72, 0x18, 0x3d, 0x1f, 0xe1,
	0x0c, 0xa8, 0xa4, 0x99, 0x8f, 0xd3, 0x7d, 0x47, 0x50, 0xed, 0x08, 0xfb, 0x89, 0x37, 0x24, 0x92,
	0xce, 0x7c, 0x83, 0x40, 0xf2, 0x08, 0x23, 0x56, 0x4f, 0xba, 0x0f, 0x97, 0x83, 0x69, 0xe7, 0x49,
	0xc8, 0x62, 0x7d, 0x6d, 0xab, 0x6d, 0x9e, 0x39, 0xce, 0x66, 0xba, 0x7a, 0xe8, 0xac, 0x17, 0xf5,
	0x49, 0x26, 0x6c, 0x40, 0x7d, 0x51, 0x80, 0x68, 0xb3, 0xf5, 0xf1, 0x22, 0x14, 0x3b, 0xc2, 0xd6,
	0x5e, 0xc3, 0xfa, 0xfc, 0xa8, 0x36, 0x33, 0x9c, 0x25, 0x27, 0x4f, 0xbf, 0x97, 0x0b, 0x1e, 0x19,
	0xd0, 0xde, 0xc2, 0xb5, 0xc4, 0x94, 0x9a, 0x39, 0x5a, 0x75, 0x03, 0xa9, 0xdf, 0xcf, 0x87, 0x4f,
	0xd7, 0x56, 0x03, 0xba, 0xb4, 0x76, 0x88, 0x5f, 0x5e, 0xfb, 0xf4, 0x10, 0x69, 0xef, 0xe0, 0x7a,
	0x72, 0x80, 0xf0, 0xb2, 0xcd, 0x14, 0x41, 0x6f, 0xe7, 0x24, 0xc4, 0xf2, 0x9f, 0x10, 0x6c, 0x66,
	0xff, 0xe2, 0xdb, 0xd9, 0xad, 0x33, 0xc9, 0xfa, 0xde, 0x3f, 0x90, 0xa3, 0xcd, 0xee, 0xde, 0x8f,
	0x91, 0x81, 0x8e, 0x47, 0x06, 0xfa, 0x3d, 0x32, 0xd0, 0x87, 0xb1, 0x51, 0x38, 0x1e, 0x1b, 0x85,
	0x5f, 0x63, 0xa3, 0xf0, 0xf4, 0x8e, 0xed, 0xc8, 0x17, 0xc1, 0xc0, 0xb4, 0xb8, 0xab, 0x1e, 0x1d,
	0xb5, 0x34, 0xc5, 0xf0, 0x25, 0x3e, 0x9a, 0x79, 0xa7, 0x06, 0x97, 0xa6, 0xaf, 0xd1, 0xdd, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x07, 0xbe, 0xd4, 0x5a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// QuarantineOptIn defines a method for opting in to account quarantine.
	// Funds sent to a quarantined account must be approved before they can be received.
	QuarantineOptIn(ctx context.Context, in *MsgQuarantineOptIn, opts ...grpc.CallOption) (*MsgQuarantineOptInResponse, error)
	// QuarantineOptOut defines a method for opting out of account quarantine.
	// Any pending funds for the account must still be accepted, but new sends will no longer be quarantined.
	QuarantineOptOut(ctx context.Context, in *MsgQuarantineOptOut, opts ...grpc.CallOption) (*MsgQuarantineOptOutResponse, error)
	// AcceptSend defines a method for accepting quarantined funds.
	QuarantineAccept(ctx context.Context, in *MsgQuarantineAccept, opts ...grpc.CallOption) (*MsgQuarantineAcceptResponse, error)
	// DeclineSend defines a method for declining quarantined funds.
	QuarantineDecline(ctx context.Context, in *MsgQuarantineDecline, opts ...grpc.CallOption) (*MsgQuarantineDeclineResponse, error)
	// UpdateQuarantineAutoResponses defines a method for updating the auto-response settings for a quarantined address.
	UpdateQuarantineAutoResponses(ctx context.Context, in *MsgUpdateQuarantineAutoResponses, opts ...grpc.CallOption) (*MsgUpdateQuarantineAutoResponsesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) QuarantineOptIn(ctx context.Context, in *MsgQuarantineOptIn, opts ...grpc.CallOption) (*MsgQuarantineOptInResponse, error) {
	out := new(MsgQuarantineOptInResponse)
	err := c.cc.Invoke(ctx, "/cosmos.quarantine.v1beta1.Msg/QuarantineOptIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) QuarantineOptOut(ctx context.Context, in *MsgQuarantineOptOut, opts ...grpc.CallOption) (*MsgQuarantineOptOutResponse, error) {
	out := new(MsgQuarantineOptOutResponse)
	err := c.cc.Invoke(ctx, "/cosmos.quarantine.v1beta1.Msg/QuarantineOptOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) QuarantineAccept(ctx context.Context, in *MsgQuarantineAccept, opts ...grpc.CallOption) (*MsgQuarantineAcceptResponse, error) {
	out := new(MsgQuarantineAcceptResponse)
	err := c.cc.Invoke(ctx, "/cosmos.quarantine.v1beta1.Msg/QuarantineAccept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) QuarantineDecline(ctx context.Context, in *MsgQuarantineDecline, opts ...grpc.CallOption) (*MsgQuarantineDeclineResponse, error) {
	out := new(MsgQuarantineDeclineResponse)
	err := c.cc.Invoke(ctx, "/cosmos.quarantine.v1beta1.Msg/QuarantineDecline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateQuarantineAutoResponses(ctx context.Context, in *MsgUpdateQuarantineAutoResponses, opts ...grpc.CallOption) (*MsgUpdateQuarantineAutoResponsesResponse, error) {
	out := new(MsgUpdateQuarantineAutoResponsesResponse)
	err := c.cc.Invoke(ctx, "/cosmos.quarantine.v1beta1.Msg/UpdateQuarantineAutoResponses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// QuarantineOptIn defines a method for opting in to account quarantine.
	// Funds sent to a quarantined account must be approved before they can be received.
	QuarantineOptIn(context.Context, *MsgQuarantineOptIn) (*MsgQuarantineOptInResponse, error)
	// QuarantineOptOut defines a method for opting out of account quarantine.
	// Any pending funds for the account must still be accepted, but new sends will no longer be quarantined.
	QuarantineOptOut(context.Context, *MsgQuarantineOptOut) (*MsgQuarantineOptOutResponse, error)
	// AcceptSend defines a method for accepting quarantined funds.
	QuarantineAccept(context.Context, *MsgQuarantineAccept) (*MsgQuarantineAcceptResponse, error)
	// DeclineSend defines a method for declining quarantined funds.
	QuarantineDecline(context.Context, *MsgQuarantineDecline) (*MsgQuarantineDeclineResponse, error)
	// UpdateQuarantineAutoResponses defines a method for updating the auto-response settings for a quarantined address.
	UpdateQuarantineAutoResponses(context.Context, *MsgUpdateQuarantineAutoResponses) (*MsgUpdateQuarantineAutoResponsesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) QuarantineOptIn(ctx context.Context, req *MsgQuarantineOptIn) (*MsgQuarantineOptInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineOptIn not implemented")
}
func (*UnimplementedMsgServer) QuarantineOptOut(ctx context.Context, req *MsgQuarantineOptOut) (*MsgQuarantineOptOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineOptOut not implemented")
}
func (*UnimplementedMsgServer) QuarantineAccept(ctx context.Context, req *MsgQuarantineAccept) (*MsgQuarantineAcceptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineAccept not implemented")
}
func (*UnimplementedMsgServer) QuarantineDecline(ctx context.Context, req *MsgQuarantineDecline) (*MsgQuarantineDeclineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineDecline not implemented")
}
func (*UnimplementedMsgServer) UpdateQuarantineAutoResponses(ctx context.Context, req *MsgUpdateQuarantineAutoResponses) (*MsgUpdateQuarantineAutoResponsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuarantineAutoResponses not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_QuarantineOptIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgQuarantineOptIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).QuarantineOptIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.quarantine.v1beta1.Msg/QuarantineOptIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).QuarantineOptIn(ctx, req.(*MsgQuarantineOptIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_QuarantineOptOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgQuarantineOptOut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).QuarantineOptOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.quarantine.v1beta1.Msg/QuarantineOptOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).QuarantineOptOut(ctx, req.(*MsgQuarantineOptOut))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_QuarantineAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgQuarantineAccept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).QuarantineAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.quarantine.v1beta1.Msg/QuarantineAccept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).QuarantineAccept(ctx, req.(*MsgQuarantineAccept))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_QuarantineDecline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgQuarantineDecline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).QuarantineDecline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.quarantine.v1beta1.Msg/QuarantineDecline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).QuarantineDecline(ctx, req.(*MsgQuarantineDecline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateQuarantineAutoResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateQuarantineAutoResponses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateQuarantineAutoResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.quarantine.v1beta1.Msg/UpdateQuarantineAutoResponses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateQuarantineAutoResponses(ctx, req.(*MsgUpdateQuarantineAutoResponses))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.quarantine.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuarantineOptIn",
			Handler:    _Msg_QuarantineOptIn_Handler,
		},
		{
			MethodName: "QuarantineOptOut",
			Handler:    _Msg_QuarantineOptOut_Handler,
		},
		{
			MethodName: "QuarantineAccept",
			Handler:    _Msg_QuarantineAccept_Handler,
		},
		{
			MethodName: "QuarantineDecline",
			Handler:    _Msg_QuarantineDecline_Handler,
		},
		{
			MethodName: "UpdateQuarantineAutoResponses",
			Handler:    _Msg_UpdateQuarantineAutoResponses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/quarantine/v1beta1/tx.proto",
}

func (m *MsgQuarantineOptIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineOptIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineOptIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineOptInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineOptInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineOptInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineOptOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineOptOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineOptOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineOptOutResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineOptOutResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineOptOutResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineAccept) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineAccept) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineAccept) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Permanent {
		i--
		if m.Permanent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineAcceptResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineAcceptResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineAcceptResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineDecline) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineDecline) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineDecline) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Permanent {
		i--
		if m.Permanent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgQuarantineDeclineResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuarantineDeclineResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuarantineDeclineResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateQuarantineAutoResponses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateQuarantineAutoResponses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateQuarantineAutoResponses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for iNdEx := len(m.Updates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Updates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateQuarantineAutoResponsesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateQuarantineAutoResponsesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateQuarantineAutoResponsesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgQuarantineOptIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgQuarantineOptInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgQuarantineOptOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgQuarantineOptOutResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgQuarantineAccept) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Permanent {
		n += 2
	}
	return n
}

func (m *MsgQuarantineAcceptResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgQuarantineDecline) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Permanent {
		n += 2
	}
	return n
}

func (m *MsgQuarantineDeclineResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateQuarantineAutoResponses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Updates) > 0 {
		for _, e := range m.Updates {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateQuarantineAutoResponsesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgQuarantineOptIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineOptIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineOptIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineOptInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineOptInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineOptInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineOptOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineOptOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineOptOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineOptOutResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineOptOutResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineOptOutResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineAccept) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineAccept: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineAccept: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permanent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Permanent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineAcceptResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineAcceptResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineAcceptResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineDecline) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineDecline: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineDecline: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permanent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Permanent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQuarantineDeclineResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuarantineDeclineResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuarantineDeclineResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateQuarantineAutoResponses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateQuarantineAutoResponses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateQuarantineAutoResponses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Updates = append(m.Updates, &QuarantineAutoResponseUpdate{})
			if err := m.Updates[len(m.Updates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateQuarantineAutoResponsesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateQuarantineAutoResponsesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateQuarantineAutoResponsesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
